version: '3'
services:
  python:
    container_name: 'python.cpu.tools'
    image: akitenkrad/python.cpu.arm64:latest
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
      - data:/data
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
volumes:
  data:
    external: True
