version: '3'
services:
  python:
    container_name: 'python.cpu.tools'
    image: akitenkrad/python:cpu.base
    platform: linux/amd64 # for Apple Mac M1
    user: root
    tty: true
    volumes:
      - ../:/workplace:cached
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
